- src/pages/photo/PhotoDetail.js
- src/pages/photo/PhotoDetail.scss
- src/pages/photo/PhotoList.js
- src/pages/photo/PhotoList.scss
- src/pages/photo/PhotoPage.js
resolve #49 
사진첩 페이지 디자인을 변경합니다.
- 사진첩 배너 추가합니다.
- 대표사진 이미지 크기를 맞춥니다.
- 여백을 수정합니다.
- 사진첩 글쓰기 버튼 디자인 위치를 변경합니다.
> [feat]: 사진첩 페이지 디자인 변경 (#49)

- src/pages/notice/NoticeDetail.scss
- src/pages/notice/NoticeDetailPage.js
- src/pages/notice/NoticePage.js
resolve #58 
공지사항 디테일 페이지를 수정합니다.
- 공지사항 디테일 페이지 제목부분에 articleId 뜨던걸 제목으로 제대로 뜨도록 수정
- 공지사항 디테일 페이지 여백 및 크기 수정
- NoticeDetaile로 되어있던 코드 NoticeDetail로 수정
> [fix]: 공지사항 디테일 페이지 제목 제대로 뜨도록 수정, 여백 및 크기 수정,  코드 오타 수정

- src/pages/exam/ExamUpdate.js
- src/pages/freeBoard/FreeBoardUpdate.js
- src/pages/notice/NoticeUpdate.js
- src/pages/report/ReportUpdate.js
- src/pages/seminar/SeminarUpdate.js
- src/pages/subProject/ProjectUpdate.js
resolve #104 
사진첩 이외의 컴포넌트들에서 게시글 작성 시 **`작성취소`** 버튼을
클릭하였을 때 아무런 동작이 없었던 부분에 대하여 알맞은 기능을
추가하게 되었습니다.
- **`작성취소`** 버튼 클릭 시 게시글의 작성 취소 여부를 확인하도록
코드를 추가하였습니다.
- 게시글 작성 컴포넌트(공지사항, 자료실 내 게시판들, 자유게시판) 내용 수정이 이뤄지고 난 이후의 페이지
- 기존 공지사항 게시글 작성 컴포넌트 내에 있는 버튼 텍스트의 문구를
다른 게시판과 동일하게 수정하였습니다.
> [feat]: (게시글 작성) 컴포넌트 내 "작성취소" 버튼 기능 활성화 (#104)

- src/pages/exam/ExamDetailPage.js
- src/pages/freeBoard/FreeBoardDetailPage.js
- src/pages/notice/NoticeDetailPage.js
- src/pages/report/ReportDetailPage.js
- src/pages/seminar/SeminarDetailPage.js
- src/pages/subProject/ProjectDetailPage.js
resolve #108 
게시글 내 첨부파일 요소의 디자인을 일부 수정하였습니다.
각 게시글 디테일 컴포넌트 파일을 수정하여 디자인을
변경하였습니다.
- 변경 후 `첨부파일` 요소의 디자인
- `이전글 & 다음글` 내 특수문자(<, >)를 제거
> [fix]: 게시글 디테일 컴포넌트 내 첨부파일 요소 디자인 수정 (#108)

- public/index.html
- src/pages/exam/ExamDetail.scss
- src/pages/exam/ExamDetailPage.js
- src/pages/freeBoard/FreeBoardDetail.scss
- src/pages/freeBoard/FreeBoardDetailPage.js
- src/pages/notice/NoticeDetail.scss
- src/pages/notice/NoticeDetailPage.js
- src/pages/report/ReportDetail.scss
- src/pages/report/ReportDetailPage.js
- src/pages/seminar/SeminarDetail.scss
- src/pages/seminar/SeminarDetailPage.js
- src/pages/subProject/ProjectDetail.scss
- src/pages/subProject/ProjectDetailPage.js
resolve #110 
게시글 내용 하단에 **`좋아요`** 기능을 수행할 수 있는 UI 요소가 필요하였습니다.
- 각 게시글 디테일 컴포넌트 파일에 **`좋아요`** 요소를 추가하고자 하였습니다.
> (요소만 추가하였기 때문에 변경된 좋아요 수에 따른 값은 DB에 추가되지 않고, 게시글 조회수와 좋아요 수가 동일하게 넘어오는 문제가 있는 것 같습니다)
- 추가 후 컴포넌트 화면
> [feat]: 게시글 디테일 컴포넌트 내 "좋아요" 요소 추가 (#110)

- src/pages/exam/ExamPage.js
- src/pages/freeBoard/FreeBoardPage.js
- src/pages/notice/NoticePage.js
- src/pages/notice/NoticePage.scss
- src/pages/report/ReportPage.js
- src/pages/seminar/SeminarPage.js
- src/pages/subProject/ProjectPage.js
resolve #114 
기존 홈페이지 내 존재하는 게시판에 Pagination 기능이
필요하여 추가하였습니다.
- 각 게시글 페이지마다 15개의 글을 보여주며 DB 내에 그 이상의
글이 작성되어 있다면, 다음 게시글 페이지 버튼이 생성되어 그 외의
글들을 확인할 수 있습니다. 한 화면에 최대 10개의 게시글 페이지
수가 고정되어 있어 11페이지 이상의 생성이 이뤄지면 다음으로
11~20페이지가 나타나는 방식으로 제작하였습니다.
- 변경 후 페이지 사진 (GIF 파일이 첨부되어 있습니다)
> [feat]: 게시판 전체 Pagination 기능 추가 (#114)

- src/pages/exam/ExamPage.js
- src/pages/freeBoard/FreeBoardPage.js
- src/pages/notice/NoticePage.js
- src/pages/photo/PhotoList.js
- src/pages/report/ReportPage.js
- src/pages/seminar/SeminarPage.js
- src/pages/subProject/ProjectPage.js
resolve #122 
기존 Paignation 기능을 수행하기 위하여 사용되던 API 호출문과
요청받는 API값에 차이가 발생하여 정상적으로 데이터를 제공받지
못 하는 문제가 있었습니다.
- 각 게시글에서 사용되는 API 호출문을 알맞게 수정하였습니다.
- 기존 15개의 게시글 당 하나의 페이지로 구성되었던 부분을
가시성을 보다 높이고자 한 페이지당 10개의 게시글이 조회되도록
API 호출문 쿼리를 일부 추가하였습니다.
- 수정 후 페이지 화면(정상적으로 데이터를 받음)
> [fix]: Pagination 기능에 대한 잘못된 API 호출문 수정 (#122)

- src/pages/exam/ExamPage.js
- src/pages/freeBoard/FreeBoardPage.js
- src/pages/notice/NoticePage.js
- src/pages/report/ReportPage.js
- src/pages/seminar/SeminarPage.js
- src/pages/subProject/ProjectPage.js
resolve #129 
게시판 내에 게시글이 하나도 등록되어 있지 않을 때 페이지 넘버가
나타나지 않도록 설계했던 부분이 잘못되어 페이지 넘버가 의도와는
다르게 표시되는 버그가 발견되어 수정하였습니다.
- 각 게시판 페이지 컴포넌트 내 글 수를 확인하는 코드를 알맞게 수정
- 해결 **전**
- 해결 **후**
> [bug]: Pagination 버그 수정 (#129)

- src/components/Navigation.js
resolve #131 
서버에서 **`refreshToken`** 을 반환하지 않음에 따라 `isAuth` 함수를
호출하여 에러가 발생하였습니다.
`Navigation` 컴포넌트 내 **`isAuth`** 함수를 호출하는 코드를 제거하였습니다.
> [fix]: Navigation 컴포넌트 내 refreshToken 사용 코드 제거 (#131)

- src/pages/photo/PhotoList.js
- src/pages/report/ReportPage.js
- src/pages/seminar/SeminarPage.js
- src/pages/subProject/ProjectPage.js
resolve #133 
기존 게시글 정보를 조회할 때 사용하는 API가 변경됨에 따라서
데이터를 조회할 때 참조하는 속성이 추가되었지만, 해당 사항이
기존의 몇몇 코드에는 반영되어 있지 않아 특정 게시판 내에서는
정상적으로 등록된 게시글들이 표시되지 않는 문제가 있었습니다.
- `세미나`, `활동 보고서`, `소규모 프로젝트`, `사진첩` 게시판  컴포넌트 코드 내
최신 기준의 API를 호출 시 받아오는 값으로 참조가 가능하게끔 알맞게 코드를 수정하였습니다.
- 해결 후 사진(정상적으로 게시판 내 게시글을 불러옴)
> [bug]: 특정 게시판 내 게시글 정보 조회 시 발생하는 버그 제거 (#133)

- src/hooks/useAuth.js
- src/pages/exam/ExamPage.js
- src/pages/exam/ExamUpdate.js
- src/pages/freeBoard/FreeBoardPage.js
- src/pages/freeBoard/FreeBoardUpdate.js
- src/pages/main/Board.js
- src/pages/management/ManagementPage.js
- src/pages/modifyUserInfo/CheckPwPage.js
- src/pages/notice/NoticePage.js
- src/pages/notice/NoticeUpdate.js
- src/pages/photo/PhotoList.js
- src/pages/photo/PhotoPage.js
- src/pages/photo/PhotoUpdate.js
- src/pages/report/ReportPage.js
- src/pages/report/ReportUpdate.js
- src/pages/seminar/SeminarPage.js
- src/pages/seminar/SeminarUpdate.js
- src/pages/subProject/ProjectPage.js
- src/pages/subProject/ProjectUpdate.js
resolve #128 
로그인 후 유저의 권한에 따라 특정 작업을 수행  또는 차단되도록 하여야
하는데, 해당 부분에 대하여 모호한 컴포넌트들이 확인하였습니다.
- `비회원`에 대한 권한 처리가 가능하도록 코드 수정
- `관리자 페이지` 컴포넌트에 접근 시 유저 권한에 알맞게 접근이 가능하도록 코드 수정
- `정보 수정` 컴포넌트에 접근 시 유저 권한에 알맞게 접근이 가능하도록 코드 수정
- `자유게시판` 컴포넌트에 접근 시 유저 권한에 알맞게 접근이 가능하도록 코드 수정
- `공지사항` 컴포넌트에 접근 시 유저 권한에 알맞게 접근이 가능하도록 코드 수정
- `특강자료` 컴포넌트에 접근 시 유저 권한에 알맞게 접근이 가능하도록 코드 수정
- `활동 보고서` 컴포넌트에 접근 시 유저 권한에 알맞게 접근이 가능하도록 코드 수정
- `소규모 프로젝트` 컴포넌트에 접근 시 유저 권한에 알맞게 접근이 가능하도록 코드 수정
- `족보` 컴포넌트에 접근 시 유저 권한에 알맞게 접근이 가능하도록 코드 수정
- `사진첩` 컴포넌트에 접근 시 유저 권한에 알맞게 접근이 가능하도록 코드 수정
> [fix]: 컴포넌트 별로 유저의 권한에 알맞게 접근 또는 차단되도록 수정 (#128)

- src/hooks/boardServices.js
- src/pages/exam/ExamPage.js
- src/pages/exam/ExamUpdate.js
- src/pages/freeBoard/FreeBoardPage.js
- src/pages/freeBoard/FreeBoardUpdate.js
- src/pages/notice/NoticePage.js
- src/pages/notice/NoticeUpdate.js
- src/pages/photo/PhotoList.js
- src/pages/photo/PhotoUpdate.js
- src/pages/report/ReportPage.js
- src/pages/report/ReportUpdate.js
- src/pages/seminar/SeminarPage.js
- src/pages/seminar/SeminarUpdate.js
- src/pages/subProject/ProjectPage.js
- src/pages/subProject/ProjectUpdate.js
resolve #145 
각 게시판 별로 사용되고 있는 `게시글 업데이트` 컴포넌트 내에
위치한 `작성취소` 버튼이 해당 페이지 접속 시 자동적으로 호출
되고, 취소 확인 시 이전 페이지로 이동되지 않는 버그 와 refactoring
과정 중 게시글 호출과 관련한 API가 올바르게 호출되지 못 하여 발생된
버그가 발견되었습니다.
- `각 게시판 별 게시글 업데이트` 컴포넌트
- `boardServices.js` 파일
> [bug]: 게시글 내 "작성취소" 버튼 기능 및 Pagination API 호출문 에러 수정 (#145)

- src/pages/photo/PhotoList.js
resolve #159 
사진첩 게시판 내에 게시글이 하나도 등록되어 있지 않을 때 페이지 넘버가
나타나지 않도록 설계했던 부분이 잘못되어 페이지 넘버가 의도와는 다르게
표시되는 버그가 발견되었습니다.
- **`PhotoList.js`** 컴포넌트 내 코드 수정
- 해결 전 사진
- 해결 후 사진
> [bug]: 사진첩 게시판 내 Pagination 버그 수정 (#159)

- src/components/Comment.js
- src/hooks/useAuth.js
- src/pages/exam/ExamUpdate.js
- src/pages/freeBoard/FreeBoardUpdate.js
- src/pages/management/BoardManage.js
- src/pages/management/MemberManage.js
- src/pages/management/ScheduleManage.js
- src/pages/modifyUserInfo/CheckPwPage.js
- src/pages/modifyUserInfo/ModifyUserInfoPage.js
- src/pages/notice/NoticeUpdate.js
- src/pages/photo/PhotoUpdate.js
- src/pages/report/ReportUpdate.js
- src/pages/seminar/SeminarUpdate.js
- src/pages/subProject/ProjectUpdate.js
resolve #179 
- 현재 홈페이지 내에서 accesstoken 만료 후 API를 호출하면
에러가 발생하는데, 사용자 입장에서는 별도의 안내 문구를 보여주지
않으면 왜 에러가 발생하였는지 인지하여 못 하기 때문에 해당 문제를 보안하기
위한 코드를 추가하였지만, 모듈화가 되어 있지 않아 API를 호출하는
모든 컴포넌트 내에서 해당 코드를 반복적으로 사용하여 불필요하게 코드 라인이
늘어나 refactoring을 염두에 두게 되었습니다.
- accesstoken 만료 여부를 확인하고 처리하는 코드를 특정 파일 내에 정의하고 기존에
해당 코드를 사용하는 모든 컴포넌트 내에서 위 함수를 호출하는 방법으로 수정
- `회원관리` 컴포넌트 내 **`검색`** 버튼의 색이 다소 연하게 좀 더 진한 색으로 변경하였습니다.
- `회원관리` 컴포넌트 내 **`검색`** 버튼 클릭 시 API로부터 받아오는 값을 알맞은 형태로
받지 않고 있던 오류가 발견되어 알맞게 수정하였습니다.
- 결과 화면
- `검색 버튼` 색상 변경 전
- `검색 버튼` 색상 변경 후
-
> [refactor]: Accesstoken 만료 확인 후 토큰 제거 기능 모듈화 및 회원검색 오류 제거 (#179)

- src/pages/findUser/FindUserPage.js
resolve #184 
임시 비밀번호 생성 컴포넌트에서 DB에 등록되지 않은 이메일로 정보 조회 시도 시
발생하는 문제에 대하여 사용자에게 안내가 되도록 문구를 추가하고자 하였습니다.
- **`FindUserPage.js** 파일 내 예외처리 문장 추가
- 수정 전
- 수정 후
(밑 사진은 존재하지 않는 이메일로  `확인` 버튼 클릭 시 나타나는 문구)
(밑 사진은 비회원인 상태에서 API 사용 시 발생하는 에러에 대한 문구인데, 원래 임시 비밀번호 생성 API의 경우에는 별도로 권한을 필요로 하지 않기 때문에 필요하지 않은 코드이지만, 현재 백엔드 코드 버전에서는 로그인된 상태에서만 해당 API가 사용 가능하기 때문에 예외 처리 코드를 별도로 추가해 준 상태입니다.)
> [fix]: 존재하지 않는 이메일로 임시 비밀번호 생성 API 사용 시 발생하는 에러에 대한 안내 문구 추가 (#184)

- src/pages/exam/ExamPage.js
resolve #186 
비회원인 상태에서 족보 게시판 내 게시글이 확인되는
문제가 있었습니다.
- **`ExamPage.js`** 파일 내에 액세스 토큰 여부에 따라
그 다음 코드가 처리되도록 조건식을 추가함.
- 해결 전
- 해결 후
> [fix]: 비회원 유저의 족보 게시판 내 게시글 열람 차단 조건식 추가 (#186)

- src/Router.js
- src/components/Navigation.js
- src/pages/exam/ExamPage.js
resolve #189 
비회원인 상태에서 족보 게시판에 접근이 가능한
문제가 있어서 해당 문제를 수정하였습니다.
- **`Navigation.js`** , **`Router.js`** 파일** 내 접근 차단 코드 추가
- 수정 전
- 수정 후
> [fix]: 비회원 족보 게시판 접근 차단 (#189)

- src/components/Comment.js
- src/components/Comment.scss
resolve #192 
현재 댓글 기능 중에는 작성만 가능하기 때문에 수정 및 삭제가
가능하도록 API를 적용하여 요소 및 기능을 추가하였습니다.
- **`Comment.js`** 및 **`Comment.scss`** 파일을 수정하여
댓글 수정 및 삭제 대한 기능을 수행할 수 있도록 함
- 추가 전
- 추가 후(내용이 길어질 경우에 스크롤이 가능하도록 함)
> [feat] 댓글 (수정 & 삭제) 요소 및 기능 추가 (#192)

- src/hooks/boardServices.js
resolve #194 
게시글 열람 시 액세스 토큰 시간 만료 후 새로고침을 하면
API호출이 제한되는데, 이를 무시하고 호출이 이뤄지게 되면
버그가 발생하고  이에 대한 처리가 가능하도록 작업하였습니다.
- **boardServices.js``** 파일 내 API 호출 시 액세스 토큰이
만료되어 있는 상태라면 자동으로 로그인 페이지로 이동되도록 함.
- 에러 사진
- 게시글 내에서 액세스 토큰 만료 후 새로고침 시 로그인 페이지로 이동되도록 함
> [bug]: Accesstoken 만료 시 게시글 내에서 API 호출로 인해 발생하는 버그 수정 (#194)

- src/hooks/useAuth.js
resolve #197 
홈페이지 내에서 Accesstoken이 만료된 이후
로그아웃 버튼을 클릭하여 로그아웃 API 호출 시
이미 API 호출 권한이 없는 상태이기 때문에 발생
하는 에러를 제거하고자 하였습니다.
- **`useAuth.js`** 컴포넌트 내 signout함수 내에서
기존의 `logout` API 호출 없이도 delCookie 함수를 이용하여
로그아웃 기능을 구현할 수 있었기에 해당 API 호출 코드를 delCookie
함수로 대체하여 버그를 제거하였습니다.
- 해결 후
> [bug]: Accesstoken 만료 후 로그아웃 버튼 클릭 시 발생하는 에러 제거 (#197)

- public/assets/css/main.css
- src/pages/main/Board.js
- src/pages/main/MainPage.js
resolve #198 
기존 메인페이지 내에 위치한 공지사항 게시판에는
화면 높이 내에 표시되는 게시글들만 확인할 수 있었기에
추가로 등록되어 있는 글들을 열람할 수 있도록 `더 보기`
버튼을 추가하고자 하였습니다.
- `더 보기` 버튼 클릭 시 공지사항 게시판 컴포넌트로 이동할 수
있도록 코드를 추가하였습니다.
- 추가 후(GIF 파일이 업로드 되어 있어 불러오는 데 시간이 다소 소요될 수 있습니다)
> [feat]: 메인 페이지 공지사항 내 "더 보기" 요소 추가 (#198)

- src/pages/exam/ExamDetailPage.js
- src/pages/freeBoard/FreeBoardDetailPage.js
- src/pages/notice/NoticeDetailPage.js
- src/pages/photo/PhotoDetail.js
- src/pages/report/ReportDetailPage.js
- src/pages/seminar/SeminarDetailPage.js
- src/pages/subProject/ProjectDetailPage.js
resolve #210 
게시글 작성 시 개행을 포함한 이스케이프 시퀀스가 열람 시
적용되지 않고 표시되는 문제점이 발견되어 수정이 필요하였습니다.
- 모든 게시글 디테일 컴포넌트 내에서 게시글의 내용을 표시하는
부분은 **`pre`** 태그로 감싸 이스케이프 시퀀스가 적용될 수
있도록 하였습니다.
- 수정 후
https://user-images.githubusercontent.com/56868605/200549315-c6c09125-ecab-47b3-9a4e-8ea4ace51926.mov
> [bug]: 게시글 내용 확인 시 이스케이프 시퀀스 처리가 되지 않았던 문제 수정 (#210)

- src/Router.js
- src/hooks/useAuth.js
- src/pages/exam/ExamPage.js
- src/pages/freeBoard/FreeBoardPage.js
- src/pages/notice/NoticePage.js
- src/pages/photo/PhotoList.js
- src/pages/report/ReportPage.js
- src/pages/seminar/SeminarPage.js
- src/pages/subProject/ProjectPage.js
resolve #217 
현재 로그인이 되어 있지 않은 사용자의 경우 홈페이지 내 게시판 접근 시
정상적으로 접근이 가능하고, 게시글 목록 조회가 가능하였는데, 이 부분에
대하여 제한을 둘 수 있도록 작업하였습니다.
- 비회원의 게시판 접근 시 이를 제한하고, 로그인 페이지로 이동될 수 있도록 합니다.
- 작업 이전의 상황
https://user-images.githubusercontent.com/56868605/204612183-a2759343-a5fd-4f5b-9550-5add35aab4d2.mov
- 작업 이후
https://user-images.githubusercontent.com/56868605/204612449-a360006f-c21c-4b11-bfa2-c183fef127af.mov
> [feat]: 비회원 유저의 게시판 접근 시 내부 게시글 열람 및 접근 제한 기능 추가 (#217)

- src/pages/management/MemberManage.js
- src/pages/management/MemberManage.scss
resolve #219 
현재 홈페이지 내에서 사용자가 회원가입을 완료하였을 때 회원 목록에
자동적으로 등록되는데, 올바르지 않은 회원에 대하여 추방을 진행할 수
있는 기능을 수행하고자 해당 작업에 필요한 요소 추가였습니다.
- **`MemberManage.js`** 컴포넌트 내 `회원제거` 칼럼 추가 및
각 행 별 `추방` 버튼 요소 추가
- 추방 버튼 클릭 시 예외처리 및 회원 삭제 기능을 수행
- 작업 후
https://user-images.githubusercontent.com/56868605/205456942-9bef464b-4426-4035-87ac-cfd5bfe365f5.mov
> [feat]: 관리자 페이지의 회원 관리 탭 내부 테이블 내에 (회원 추방 기능) 추가 (#219)

- src/pages/main/MainPage.js
resolve #221 
현재 메인페이지 컴포넌트 상단에 위치한 `WELCOME TO SAMMARU` 텍스트
클릭 시 `https://sammaru.cbnu.ac.kr/index.html`로 이동되는 기능이 적용되어있어
`동아리 소개` 컴포넌트를 불러올 수 있도록 코드를 수정하였습니다.
- **`MainPage.js`** 컴포넌트 내 a 태그를 Link 태그로 변경
- url을 `https://sammaru.cbnu.ac.kr/clubIntro`가 되도록 코드 수정
- 기능 수정 전
- 기능 수정 후
> [fix]: WELCOME TO SAMMARU 클릭 시 '동아리 소개' 페이지로 이동되도록 기능 수정 (#221)

- src/components/Navigation.js
- src/components/Navigation.scss
- src/pages/login/LoginPage.js
- src/pages/login/LoginPage.scss
resolve #223 
홈페이지 메인페이지 우측 상단에 위치한 `회원가입/로그인` UI 요소의
가시성이 낮다는 의견을 받아 해당 UI 요소의 디자인 변경 및 LoginPage
컴포넌트 내 특정 UI 요소의 디자인을 추가적으로 변경하였습니다.
- **`Navigation.js`** 컴포넌트 내 위치한 "회원가입/로그인" 요소 디자인 변경
- **`LoginPage.js`** 컴포넌트 내 로그인 버튼 디자인 변경, `아이디/비번 찾기` 텍스트 수정
- 회원가입 링크 요소 추가
- 변경 전 사진(`회원가입/로그인` 요소)
- 변경 후 사진(`회원가입/로그인` 요소)
---
- 변경 전 사진(`로그인 페이지`)
- 변경 후 사진(`로그인 페이지`)
> [fix]: 메인페이지 내 (회원가입/로그인) 및 (LoginPage 컴포넌트) UI 요소 디자인 변경 (#223)

- src/pages/management/MemberManage.js
resolve #225 
현재 관리자페이지 내 회원 관리 테이블에 위치한 `추방` 버튼 클릭 시
특정 문구와 함께 추방 여부를 다시금 확인하는 창이 나타나는데, 회원
삭제 완료 후 나타나는 창 내의 아이콘이 다소 모호하여 해당 부분을 알맞은
아이콘으로 변경하였습니다.
- **`MemberManage.js`** 컴포넌트 내 `Swal.fire`의
icon 속성을 기존 `info`에서 `success`로 변경하였습니다.
- 기존 화면
- 수정 후 화면
> [fix]: 회원 관리 테이블 내 추방 버튼 클릭 시 나타나는 문구 아이콘 변경 (#225)

- public/assets/css/main.css
- src/components/Footer.js
- src/pages/login/LoginPage.js
- src/pages/login/LoginPage.scss
resolve #240 
로그인 페이지 디자인 스타일을 변경하고자 하였습니다.
- `LoginPage.js` 파일 내 입력 폼 관련 요소 추가 및 수정
- `LoginPage.scss` 파일 수정에 따른 스타일 변경
- `Footer.js` 파일 내 깃헙 아이콘 요소의 class -> className으로 속성명 수정
- `main.css` 파일 내 input 요소의 배경색 스타일을 지정하는 속성 제거
- 수정 전
- 수정 후 (처음: 자동완성[autocomplete]이 적용된 경우, 이후: Chrome 시크릿 모드로 저장된 아이디, 비밀번호 데이터가 없는 초기 상태에서 로그인 페이지에  접근하였을 경우로 구분 지어 녹화하였습니다)
https://user-images.githubusercontent.com/56868605/209346497-b90a086d-84ee-4491-a646-65bbcfed5e13.mov
> [fix]: 로그인 페이지 스타일 수정 (#240)

- src/components/Footer.js
- src/components/UploadedFilesInArticle.js
- src/pages/exam/ExamDetail.scss
- src/pages/exam/ExamDetailPage.js
- src/pages/exam/ExamUpdate.js
- src/pages/freeBoard/FreeBoardDetail.scss
- src/pages/freeBoard/FreeBoardDetailPage.js
- src/pages/freeBoard/FreeBoardUpdate.js
- src/pages/notice/NoticeDetail.scss
- src/pages/notice/NoticeDetailPage.js
- src/pages/notice/NoticeUpdate.js
- src/pages/report/ReportDetail.scss
- src/pages/report/ReportDetailPage.js
- src/pages/report/ReportUpdate.js
- src/pages/seminar/SeminarDetail.scss
- src/pages/seminar/SeminarDetailPage.js
- src/pages/seminar/SeminarUpdate.js
- src/pages/subProject/ProjectDetail.scss
- src/pages/subProject/ProjectDetailPage.js
- src/pages/subProject/ProjectUpdate.js
resolve #203
게시글 컴포넌트 하단에 배치되어 있는 `첨부파일` 요소의
디자인을 변경하여 좀 더 깔끔하게 변경하고자 하였습니다.
- 첨부파일 컴포넌트 추가
- `공지사항` 게시판 게시글 내 첨부파일 란 디자인 수정
- `자유게시판` 게시판 게시글 내 첨부파일 란 디자인 수정
- `특강자료` 게시판 게시글 내 첨부파일 란 디자인 수정
- `활동보고서` 게시판 게시글 내 첨부파일 란 디자인 수정
- `소규모 프로젝트` 게시판 게시글 내 첨부파일 란 디자인 수정
- `족보` 게시판 게시글 내 첨부파일 란 디자인 수정
- `Footer.js` 컴포넌트 내 깃헙 아이콘 요소의 class -> className 속성명 변경
- 변경 전 `첨부파일`
- 변경 후 `첨부파일`
- <img width="1151" alt="Screenshot 2022-12-24 at 4 48 12 PM" src="https://user-images.githubusercontent.com/56868605/209439182-04c97c61-a121-4c5f-8922-c1c9797574cc.png">
> [fix]: 게시글 내 첨부파일 요소 디자인 변경 (#203)

- src/pages/exam/ExamUpdate.js
- src/pages/freeBoard/FreeBoardUpdate.js
- src/pages/notice/NoticeUpdate.js
- src/pages/report/ReportUpdate.js
- src/pages/seminar/SeminarUpdate.js
- src/pages/subProject/ProjectUpdate.js
resolve #243 
현재 사진첩 게시판을 제외한 모든 게시판 내에서 게시글 등록 과정 중 파일
첨부 시 HTML 요소의 unique key 속성에 대한 부분이 설정되어 있지 않아
warning이 발생하여 해당 문제를 제거하고자 하였습니다.
- 사진첩 게시판을 제외한 모든 게시판 내 `게시글 작성 컴포넌트`(~~Update.js) 내
`ListGroup.Item` 컴포넌트의 속성에 map 메서드 두 번째 인자인 id 값을 기반으로 key를
설정하여 해당 warning을 제거하였습니다.
- 문제 warning
- warning 제거 후
> [bug]: 게시글 등록 중 파일 첨부 시 발생하는 warning 제거 (#243)

- src/components/Comment.jsx
resolve #247 
현재 게시글 내 위치한 `댓글` 컴포넌트의 (수정, 삭제) 기능을 수행하려면,
해당 댓글을 게시한 사용자 혹은 관리자에 한하여 이용이 가능한데, 현재
컴포넌트 로직 상으로, `댓글 게시자 이름`이 **동일하면** 위 두 기능들을 정상적으로
사용 가능하게 설정되어있어, 다른 사용자일지라도 같은 유저명으로 회원가입이 된다면,
다른 이의 댓글 (수정, 삭제) 악용 가능성이 발생할 수 있어 동일 유저명이 아닌, DB 내
기본키로 사용되고 있는 userId를 기반으로 (수정, 삭제) 기능을 이용할 수 있도록 코드를
수정하였습니다.
- **`Comment.js`** 파일 내 댓글 (수정, 삭제) 기능 사용 로직을 기존 유저명에서 **userId**로 변경합니다.
- **`Comment.js`** 파일 내 불필요한 span 요소를 제거합니다.
- 기존 댓글 (수정, 삭제) 허용 로직
- 수정 후 댓글 (수정, 삭제) 허용 로직
> [fix]: 게시글 댓글 '수정 & 삭제' 기능 사용의 대상 설정 로직 수정 (#247)

- public/assets/css/main.css
- src/pages/main/Board.scss
- src/pages/management/MemberManage.jsx
- src/pages/management/MemberManage.scss
resolve #249 
지난 동아리 회원에 대한 `이름` 및 `이미지`가 홈페이지에 추가되어
있는 상태인데, 그 이후부터 가입한 회원에 대해서는 별도의 기수 관리가
되지 않아 해당 페이지에 추가가 되지 못 했던 문제가 있어 해당 작업을
추후에 이어서 수행 가능하도록 기수 추가 기능을 추가하였습니다.
- 관리자는 `관리자 페이지` 내에서 현재 홈페이지에 가입한 회원에 대한 기수 설정 기능이 추가됩니다.
- 관리자페이지 회원관리 메뉴 내 table 요소의 디자인이 변경됩니다.
- 메인페이지 내 공지사항 table 요소의 디자인이 변경됩니다.
- 이전의 관리자 페이지 내 `회원관리` 메뉴 탭의 구성
- 이전의 메인페이지 내 공지사항 테이블 디자인
- 추가 후 관리자페이지 내 `회원관리` 메뉴 탭 테이블
- 수정 후 메인페이지 내 공지사항 테이블 디자인
> [feat]: 관리자의 사용자 기수 설정 기능 추가 (#249)

- src/Router.jsx
- src/pages/exam/ExamDetailPage.jsx
- src/pages/exam/ExamPage.jsx
- src/pages/freeBoard/FreeBoardDetailPage.jsx
- src/pages/freeBoard/FreeBoardPage.jsx
- src/pages/notice/NoticeDetailPage.jsx
- src/pages/notice/NoticePage.jsx
- src/pages/photo/PhotoDetail.jsx
- src/pages/photo/PhotoList.jsx
- src/pages/photo/PhotoPage.jsx
- src/pages/report/ReportDetailPage.jsx
- src/pages/report/ReportPage.jsx
- src/pages/seminar/SeminarDetailPage.jsx
- src/pages/seminar/SeminarPage.jsx
- src/pages/subProject/ProjectDetailPage.jsx
- src/pages/subProject/ProjectPage.jsx
resolve #251 
현재 홈페이지에서 게시글 열람 후 웹 브라우저의 뒤로가기 기능 사용 시
해당 페이지에 접근하기 이전 pagination 번호를 별도로 저장해 두지 않아
다시 1페이지로 초기화되는 불편함이 있어 해당 문제를 제거하고자 pagination 번호
유지 기능을 추가하고자 하였습니다.
- 게시글 내에서 `뒤로가기` 기능 사용 시 이전 게시글 pagination 번호가 유지되도록
게시글 컴포넌트 내에서 `뒤로가기 기능 감지 이벤트` 코드를 추가하여 해당 기능을 구현하였습니다.
- 게시글 내 하단에 `목록`버튼 클릭 시 이전 게시글 pagination 번호가 유지되도록 코드를 추가하였습니다.
- 이전의 불편 사항 시연
- 기능 추가 후
> [feat]: 게시글 페이지에서 '뒤로가기' 기능 사용 시 Pagination 번호 유지 기능 추가 (#251)

- src/pages/findUser/FindUserPage.jsx
resolve #254 
현재 홈페이지에서 회원가입한 이력이 있는 사용자가 본인의
비밀번호를 분실한 경우 `비밀번호 찾기` 기능을 통하여 input 창에
입력한 이메일에 해당하는 계정에 새로운 비밀번호를 부여해 주는데, 만일
DB에 존재하지 않는 이메일을 입력하여 API를 사용하려는 경우에는
`해당 회원은 존재하지 않습니다.` 라는 Alert를 띄워주지만, 해당 로직이
`http response`의 실패 여부에 따라서 나타나도록 코드가 설계되어 있어
`존재하지 않는 이메일` 에러 외의 에러는 별도로 구분할 수가 없어 해당
문제 방지하고자 상황에 따른 에러를 구분할 수 있도록 `http response status code`를
기반으로 Alert가 나타나도록 로직을 수정하였습니다.
- `FindUserPage.jsx` 코드 내 `해당 회원은 존재하지 않습니다.` 에러 Alert를 `http response status code`를 기준으로 나타날 수 있도록 코드를 수정합니다.
- 기존 로직
- 수정 후 로직
---
> [fix]: 임시 비밀번호 생성 API 사용 관련 Alert 표시 로직 변경 (#254)

- src/pages/exam/ExamDetail.scss
- src/pages/exam/ExamDetailPage.jsx
- src/pages/freeBoard/FreeBoardDetail.scss
- src/pages/freeBoard/FreeBoardDetailPage.jsx
- src/pages/notice/NoticeDetail.scss
- src/pages/notice/NoticeDetailPage.jsx
- src/pages/notice/NoticePage.jsx
- src/pages/photo/PhotoDetail.jsx
- src/pages/photo/PhotoDetail.scss
- src/pages/report/ReportDetail.scss
- src/pages/report/ReportDetailPage.jsx
- src/pages/seminar/SeminarDetail.scss
- src/pages/seminar/SeminarDetailPage.jsx
- src/pages/subProject/ProjectDetail.scss
- src/pages/subProject/ProjectDetailPage.jsx
resolve #260 
현재 게시글 내에서 글의 내용이 한 줄로 길 경우에는 줄바꿈이 이뤄지지 않고
슬라이드 바가 생겨 작성한 텍스트를 확인하도록 되어 있는데, 이런 경우에는
자동으로 줄바꿈이 되도록 하여 사용자가 별도의 슬라이딩 없이 텍스트를 한 화면
내에서 확인할 수 있도록 글 내용 UI 요소 스타일링 코드를 수정하였습니다.
- 게시글 관련 컴포넌트 내 게시글 내용 요소 태그 수정(**`pre`** -> **`span`**)
- 게시글 관련 컴포넌트 전용 SCSS 파일 스타일링 코드 수정
- 이전 페이지 (**`GIF`** 파일 첨부)
- 수정 후 페이지 (Enter 키 입력 없이 한 줄로 긴 텍스트 입력 시에도 자동 개행이 적용됨)
> [fix]: 게시글 내용 슬라이드 바 제거 (#260)

- src/pages/findUser/FindUserPage.jsx
resolve #266 
현재 `임시 비밀번호 생성 API`를 사용하려면 `/auth/tempPassword` URL으로
HTTP request를 진행하여야 하는데, #254 이슈 작업 중 **`8159db6(commit ID)`**
> [[FIX] 임시 비밀번호 생성 API 사용 관련 Alert 표시 로직 변경 #254](https://github.com/SAMMaru5/SAMMaruClient/pull/255/commits/0928d5ddb8d6fe294e83e5aa7e9960a8abb233f7)
올바르지 않은 URL작성으로 인하여 해당 API 사용이 불가했던 버그가 발견되어
수정하였습니다.
- `src/pages/findUser/FindUserPage.jsx` 파일 내 17번 째 코드 라인 (`/tempPassword?userEmail...`)
```javascript
await api.post("/tempPassword?userEmail=" + email).then((response) => {
```
- 버그 수정 후(`임시 비밀번호 생성 API` 정상적으로 사용 가능)
> [bug]: 클라이언트 코드 내 (임시 비밀번호 생성 API) URL 올바르게 수정 (#266)

- src/utils/api.js
resolve #274 
로그인 이후에 발급된 JWT accesstoken의 만료시간이 지난 후에 웹 브라우저
localstorage의 데이터들이 초기화되지 않고 그대로 남아 만료된 accesstoken을
사용하여 API를 사용하는 상황으로 인하여 버그가 발생하여, accesstoken의 만료 시간
2분 전에 API 호출이 발생하면 reissue API를 이용하여 accesstoken을 새롭게 발급받고,
만료 시간 이후에 API 호출이 일어났을 때에는 웹 브라우저 localstorage가 초기화되도록
하였습니다.
- accesstoken 만료시간 2분 전에 API 호출이 일어나면 reissue 요청
- accesstoken 만료시간 이후에 API 호출이 일어나면 웹 브라우저 localstorage 초기화
- 문제 예시
> [bug]: 만료된 JWT 토큰을 이용한 API 사용으로 인해 발생하는 버그 제거 (#274)

- src/components/Comment.jsx
- src/hooks/usePostServices.js
- src/pages/management/MemberManage.jsx
- src/utils/api.js
resolve #276 
#275 이슈 작업 이후에 기능 테스트 중 게시글 상세 컴포넌트 내에서 `accessstoken` 만료시간 이전에(만료 2분 전)  `reissue` 요청이
일어나면, 새롭게 발급된 accesstoken으로 게시글 상세 정보를 불러오는 것이 아닌, 이전에 만료되었던 accesstoken을 기반으로
API 호출이 일어나 에러가 발생하고, 로그인 페이지로 넘어가는 문제가 있었습니다. 추가적으로, 현재 프로젝트에서 불필요하게 사용되는 `console.log` 메서드를 일괄적으로 제거하고자 하였습니다.
- 인터셉터 내부 reissue API 호출에 대한 예외처리 코드 추가
- `console.log` 메소드가 사용되는 파일 내부 해당 메서드 제거
- 수정이 필요한 현상
https://user-images.githubusercontent.com/56868605/218242617-8f1e57ee-8c51-488d-bde8-86309382c391.mov
- reissue가 여러 번 발생함
>  <img width="842" alt="Screenshot 2023-02-11 at 2 50 37 PM" src="https://user-images.githubusercontent.com/56868605/218242868-f5661aa2-2fa0-4ed0-a3de-9116875f52af.png">
- 해결 후 (로그인 페이지로 이동되지 않음)
https://user-images.githubusercontent.com/56868605/218245491-e853b875-9500-4b5a-86bd-9afa542 …
> [fix]: 게시글 상세 컴포넌트 내에서 reissue 발생 후 로그인 페이지로 이동되는 현상 수정 및 불필요 console.log 메서드 제거 (#276)

- src/pages/login/LoginPage.jsx
- src/utils/api.js
resolve #278 
홈페이지 내에서 로그인 시 서버로부터 `accesstoken`, `refreshtoken`, `accessTokenExpiresTime`을 받아와
로컬 스토리지 공간에 저장하여 별도로 관리하였는데, refreshtoken을 쿠키에 보내는 방법으로 변경됨에 따라 프론트
interceptor 코드를 일부 수정하고자 하였습니다.
- `src/utils/api.js` 파일 내 **request interceptor** 정의 코드 내부 `reissue` API 호출 시 기존 refreshtoken 관련 코드 제거 및 `withCredentials` 옵션 `true`로 설정
- `login` API 호출 시 HTTP response, `refreshtoken`이 없어짐에 따라 `localstorage` 내 `refreshtoken` 값을 저장하는
코드 제거
- 적용 환경 (만료시간 2분 전 새로고침[+ 다른 API 호출 시]을 하여 `reissue` API가 요청되고 클라이언트 측 `localstorage`의 `accesstoken` 및 `만료시간`이 정상적으로 갱신됨)
> [fix]: JWT 인증 방식 변경에 따른 interceptor 코드 수정 (#278)

- src/pages/management/MemberManage.jsx
- src/pages/management/MemberManage.scss
resolve #280 
현재 프로젝트 계획 상, 일반 유저의 경우 비밀번호를 제외한 별도의 개인정보 수정이
불가하기 때문에 관리자가 홈페이지 내 가입되어 있는 회원들의 정보를 변경할 수 있도록
별도의 UI 요소를 관리자페이지 회원 탭 페이지 내에 추가하였습니다.
- 관리자페이지 `회원 탭`에 회원명, 이메일, 학번을 수정할 수 있는 UI가 추가됩니다.
- 현재 관리자 페이지 내 `회원 관리` 탭
- 기능 추가 후 `회원 관리` 탭
> [feat]: 관리자 페이지 내 회원정보 수정 UI 요소 추가 (#280)

- src/pages/photo/PhotoList.jsx
- src/pages/photo/PhotoList.scss
resolve #284 
현재 홈페이지 내 `동아리 사진첩 컴포넌트`에 Pagination UI가 상단에 위치해
있는데, 게시글 내용과의 간격이 너무 좁아 불안정해 보이는 문제가 있었고,
다른 컴포넌트에서는 컴포넌트 내용 하단에 위치해 있고, 일반적으로
다른 홈페이지들의 경우에도 컴포넌트의 내용 하단에 위치해 있는 경우가 많아
기존 상단에서 하단으로 위치를 조정하였습니다.
- `PhotoList.js` 컴포넌트 내 `Pagination UI` 관련 요소 div 태그 분할
- `PhotoList.scss` 파일 내 `Pagination UI` 요소의 위치 조정을 위한 스타일 속성 변경
- 현재 동아리 사진첩 컴포넌트 내 Paginiation UI 위치 (게시글 내용 상단에 배치된 상태)
- 수정 후 동아리 사진첩 컴포넌트 내 Paginiation UI 위치 (게시글 내용 하단으로 배치)
> [fix]: 동아리 사진첩 컴포넌트 내 Pagination UI 위치 조정 (#284)

- src/hooks/useAuth.js
resolve #286 
현재 홈페이지에 로그인 함으로써 발급되는 JWT `Accesstoken`의 유효기간이
만료된 후 별도의 새로고침 동작 없이 로그아웃 버튼을 누를 시 기능이 정상적으로
작동되지 않는 버그가 발견되어 해당 문제를 제거하였습니다.
- `useAuth.js` 내 signout 함수를 Client의 JWT Accesstoken이 만료된 상태에서
호출하게 되면, `Unauthorized(401)` 에러가 발생하여 해당 에러가 발생하는 경우에는
새로고침을 통해 로컬 스토리지에 존재하던 `만료된 accesstoken`과 초기 `유효기간`이
저장된 데이터를 지움으로써 해당 버그를 제거합니다.
- 해당 버그
- 버그 제거 후(JWT Accesstken의 유효기간 만료 전/후 모두 정상적으로 로그아웃 기능이 수행됨)
> [bug]: JWT Accesstoken 만료 후 로그아웃 버튼 클릭 시 기능이 작동되지 않는 버그 제거 (#286)

- src/pages/register/RegisterPage.jsx
- src/pages/register/RegisterPage.scss
resolve #289 
현재 회원가입 컴포넌트 내에 있는 `인증번호 요청` 버튼 클릭 시
별도의 알림창과 메일이 성공적으로 발송되었을 때 이메일 입력란
하단에 인증번호 발송 요청에 대한 확인 메시지가 나타나도록 설계
되어있는데, 사용자가 `인증번호 요청` 버튼을 다시 클릭하였을 때
이전의 인증번호 요청에 대한 확인 메시지가 계속 표시되어 있어 사용자의
입장에서 새로 요청한 인증번호에 대한 확인 메시지인 것인지 혼동이 있을 수 있다고
판단되어 `인증번호 요청` 버튼을 클릭 시 이전의 이메일 입력란 하단의 확인 메시지가
초기화되도록 수정하고자 하였고, 추가적으로 이메일 인증코드 요청 시 버튼 우측에
인증코드의 유효시간을 나타내주고자 하였습니다.
- `RegisterPage.jsx` 파일 수정
- 인증코드 유효시간 UI 요소 추가
- 부적절한 이메일 형식으로 `인증코드 요청` 버튼 클릭 시 관련 안내 문구 추가
- `RegisterPage.scss` 내 인증코드 유효시간 관련 UI 요소 스타일 적용
- 이전의 `인증번호 요청` 버튼 클릭 시 이전 요청에 대한 확인 메시지가 잔존하던 상태
- 기능 수정 후(확인 메시지 잔존 이슈 해결 및 인증코드 유효시간 UI 표시)
- 인증코드 유효시간 만료 후 안내 문구 추가
- 부적절한 이메일 형식으로 `인증코드 요청` 버튼 클릭 시 관련 안내 문구 추가
> [fix]: 회원가입 컴포넌트 내 '인증번호 요청' 버튼 클릭 시 인증번호 발송 여부 확인 메시지 초기화 및 인증코드 유효시간 표시 (#289)

- src/pages/register/RegisterPage.jsx
resolve #291 
현재 회원가입 시 이메일 인증번호의 유효시간이 5분으로 설정되어 있는데,
홈페이지의 인증번호 유효시간 표시란에는 15초로 설정되어 있어서 해당 부분을
알맞게 정정하고자 하였습니다.
- `RegisterPage.jsx` 파일 수정
없습니다
> [fix]: 이메일 인증번호 유효 시간 정정 (#289)

- src/pages/management/MemberManage.jsx
- src/pages/management/MemberManage.scss
resolve #297 
현재 관리자 페이지 내 `회원관리` 컴포넌트 안에 나타나는
회원 리스트를 특정 기준이 선택되었을 때 그에 알맞게 리스트가
정렬되도록 해당 기능을 추가하였습니다.
- `회원관리` 컴포넌트 내 회원 목록을 특정 기준에 맞게 정렬할 수 있도록 기능하는 요소 추가
(학번순`(기본)`, 회원가입순, 이름순, 권한순)
- 이전 `회원관리` 컴포넌트 UI
- 회원 목록 정렬 기능 추가 후
> [feat]: 회원관리 컴포넌트 내 회원목록 정렬 기능 추가 (#297)
