src/components/Footer.js
src/components/Footer.scss
src/pages/main/Activity.js
src/pages/main/Activity.scss
src/pages/main/Board.js
src/pages/main/Board.scss
src/pages/main/ClubAwards.js
src/pages/main/ClubAwards.scss
src/pages/main/MainPage.scss
src/pages/main/Schedule.js
src/pages/main/Schedule.scss
src/pages/main/ScheduleDetaile.js
src/pages/main/ScheduleDetaile.scss

add mainPage layer

---

src/pages/register/RegisterPage.js

회원가입 버튼 클릭 시 유효성 검사 툴팁이 나오지 않던 에러 해결
현재 불필요한 레디오 버튼 주석 처리

fix validation check

---

src/components/Navigation.js
src/pages/register/RegisterPage.js

add userInfo api

---

src/pages/photo/PhotoDetail.js
src/pages/photo/PhotoList.js

resolve #18 
사진첩 상세페이지 추가
해당 게시글에 맞게 사진첩 상세 페이지 추가
✅ 참고 사항

feat : show PhotoDetailPage (#18)

---

src/pages/photo/PhotoDetail.js

resolve #18 
글 목록 이동 버튼을 추가합니다.
상세페이지에서 글 목록으로 넘어가는 버튼을 추가합니다.

feat: 상세 페이지에서 글목록 버튼 추가(#18)

---

src/pages/photo/PhotoUpdate.js
src/pages/photo/PhotoUpdate.scss

resolve #26
사진 파일 여러 개 등록하기
- 사진 파일을 여러 개 등록하여 여러 개의 사진을 미리 보기
- 여러 개의 파일 서버로 전송(API)
- 사진 등록 취소
사진 미리보기 & 사진 등록 취소
여러 개의 파일 서버로 전송

feat: 사진 파일 여러 개 등록하기 (#26)

---

src/pages/login/LoginPage.js
src/pages/management/BoardManage.js

resolve #32
로그인 페이지 input place holder 변경
로그인 페이지 input place holder 아이디 => 학번

[feat] : 로그인 페이지 input place holder 변경 (아이디 => 학번)

---

src/pages/freeBoard/FreeBoardUpdate.js
src/pages/login/LoginPage.js
src/pages/modifyUserInfo/CheckPwPage.js
src/pages/modifyUserInfo/ModifyUserInfoPage.js
src/pages/notice/NoticeUpdate.js
src/pages/photo/PhotoUpdate.js
src/pages/register/RegisterPage.js

resolve #28
버튼 클릭 시 disabled 속성 추가
- 로그인
- 회원가입
- 게시판(공지사항, 사진 게시판, 자유 게시판)
- 정보수정
- 정보수정을 위한 비밀번호 확인 페이지
해당 페이지들의 버튼에 disabled 속성 추가
로딩 중이라는 뜻으로 버튼 글씨 수정

[FIX] Button 클릭 시 disabled 속성으로 변경

---

src/pages/management/ManagementPage.js
src/pages/management/MemberManage.js
src/pages/management/MemberManage.scss

resolve #29 
회원 권한을 변경할 수 있는 페이지를 제작했습니다.
- 회원 권한 페이지 HTML & CSS 구현
- 모든 사용자 정보를 볼 수 있도록 api 구현
- 사용자 권한을 변경할 수 있도록 api 구현
- 사용자 아이디를 입력하여 볼 수 있도록 api 구현

[feat] : 회원 권한 변경 페이지 제작 (#29)

---

src/pages/findUser/FindUserPage.js
src/pages/findUser/FindUserPage.scss

resolve #34
비밀번호 찾기 페이지를 제작했습니다.
2가지 기능을 확인할 수 있습니다.
1. 해당 이메일이 존재하는가?
2. 존재한다면 해당 이메일에 임시 비밀번호를 전송합니다.

[feat]: 비밀번호 찾기 페이지 제작 (#34)

---

src/pages/main/Board.js
src/pages/main/Board.scss
src/pages/main/MainPage.js

resolve #41
수정한 메인페이지에 게시판 출력
번호, 날짜, 제목, 작성자 속성을 갖고 있는 게시판 출력

[fix]: 메인페이지에 게시판 출력 (#41)

---

src/pages/register/RegisterPage.js

resolve #40 
프론트앤드의 회원가입 정규식을 백앤드 회원가입 서비스 정규식으로 수정
변경 전
^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,20}$
변경 후
(?=.*[0-9])(?=.*[a-zA-Z])(?=.*\W)(?=\S+$).{8,20}

[fix]: 회원가입 정규식 수정, 백앤드 정규식으로 통일 (#40)

---

package.json
src/components/Navigation.js
src/pages/about/AwardsPage.js
src/pages/findUser/FindUserPage.js
src/pages/freeBoard/FreeBoardDetailPage.js
src/pages/freeBoard/FreeBoardPage.js
src/pages/freeBoard/FreeBoardUpdate.js
src/pages/main/Board.js
src/pages/main/ClubActivities.js
src/pages/main/ClubIntroduction.js
src/pages/main/MainPage.js
src/pages/management/ScheduleManage.js
src/pages/notice/NoticeDetailPage.js
src/pages/notice/NoticePage.js
src/pages/notice/NoticeUpdate.js
src/pages/photo/PhotoDetail.js
src/pages/photo/PhotoList.js
src/pages/photo/PhotoPage.js
src/pages/photo/PhotoUpdate.js

resolve #60
warning 제거
Navigation.js
NoticePage.js
NoticeDetailPage.js
FreeBoardPage.js
FreeBoardDetailPage.js
Navigation.js
NoticePage.js
NoticeDetailPage.js
FreeBoardPage.js
FreeBoardDetailPage.js
FindUserPage.js
FreeBoardUpdate.js
Board.js
ClubActivities.js
ClubIntroduction.js
MainPage.js
ScheduleManage.js
NoticeUpdate.js
PhotoDetail.js
PhotoList.js
PhotoPage.js
PhotoUpdate.js
해당 파일들의 warning 제거

[fix]: Warning 제거 (#60)

---

src/hooks/useAuth.js
src/pages/photo/PhotoDetail.js
src/pages/photo/PhotoList.js

resolve #18 
사진첩 상세페이지 기능을 추가하였습니다.
- 사진첩 상세페이지 접근시 권한 확인
- 여러장의 사진 보여주는 기능
- 사진첩 상세페이지 접근시 권한 확인
- 여러장의 사진 보여주는 기능

[feat]: 사진첩 상세페이지 권한 확인 및 사용자에게 사진 보여주는 기능 (#18)

---

src/Router.js
src/components/Navigation.js
src/pages/subProject/ProjectDetailPage.js
src/pages/subProject/ProjectPage.js
src/pages/subProject/ProjectUpdate.js

resolve #65 
소규모 프로젝트 게시판 페이지를 제작합니다.
- 소규모 프로젝트 게시판 화면을 개발합니다.
- 소규모 프로젝트 게시판 글 등록 화면을 개발합니다.
- 소규모 프로젝트 게시판 글 개별 디테일 화면을 개발합니다.

[feat]: 소규모 프로젝트 페이지 제작 (#65)

---

public/index.html
src/pages/login/LoginPage.scss
src/pages/management/MemberManage.js
src/pages/modifyUserInfo/CheckPwPage.scss
src/pages/modifyUserInfo/ModifyUserInfoPage.js
src/pages/register/AgreePage.js
src/pages/register/AgreePage.scss
src/pages/register/RegisterPage.js
src/pages/register/RegisterPage.scss

resolve #71
새로 생긴 css에 의해 다른 css의 값이 변경된 문제 해결
- 회원가입 시 동의합니다에 체크버튼 보이지 않음
- 회원가입 입력 페이지 위치
- 정보수정 비밀번호 확인 페이지 글자가 버튼 요소를 벗어나는 문제
- - 정보수정 페이지 요소 위치
- 로그인 페이지 체크박스 보이지 않음
- 회원 관리 페이지
- 
해당 페이지들의 css 수정

[fix]: main.css에 의해 발생한 css 문제 해결 (#71)

---

src/pages/exam/ExamDetailPage.js
src/pages/freeBoard/FreeBoardDetail.scss
src/pages/freeBoard/FreeBoardDetailPage.js
src/pages/notice/NoticeDetail.scss
src/pages/notice/NoticeDetailPage.js
src/pages/report/ReportDetail.scss
src/pages/report/ReportDetailPage.js
src/pages/subProject/ProjectDetailPage.js

resolve #73
게시판에서 등록한 파일을 다운로드 할 수 있도록 하였습니다.
파일이 존재할 시 a링크를 통해 다운로드 api에 접근하여 파일을 다운로드 합니다.

[feat]: 게시판에서 등록한 파일 다운로드 기능 (#73)

---

public/assets/css/main.css
src/components/Navigation.js
src/pages/main/ClubActivities.js
src/pages/main/ClubActivities.scss
src/pages/main/ClubAwards.js
src/pages/main/ClubIntroduction.js
src/pages/main/MainPage.js

resolve #75 
홈 화면에서 사용하지 않은 요소들을 수정하고, CSS를 수정합니다.
- 메인화면에서 자유게시판 탭 삭제, 스타일 조정
- 메인화면에서 샘마루 추억필름 스타일 조정
- 메인화면에서 동아리 소개 스타일 조정, 해당 페이지 연결
- 메인화면에서 수상경력 수정
- 사용안하는 navbar 탭 삭제, navbar 탭 연결 링크 수정 
메인 화면 참고바랍니다.

[fix]:  홈 화면 사용하지 않은 요소 수정 (#75)

---

src/components/Navigation.js
src/components/Navigation.scss

resolve #79 
Navbar CSS를 수정합니다.
하위탭들의 색상을 변경하였습니다.

[fix]: Navbar CSS 수정 (#79)

---

src/Router.js
src/components/Navigation.js

resolve #81
샘마루 회원 기수페이지 url 변경할 것을 피드백 받았습니다.
/member/1 과 같이 변경하였습니다.

[fix]: 샘마루 회원 기수페이지 url 변경 (#81)

---

src/pages/photo/PhotoDetail.js
src/pages/photo/PhotoDetail.scss
src/pages/photo/PhotoList.js
src/pages/photo/PhotoList.scss
src/pages/photo/PhotoPage.js
src/pages/photo/PhotoUpdate.js
src/pages/photo/PhotoUpdate.scss

resolve #85 
사진첩 페이지를 디자인니다.
- 사진첩 게시판 화면을 디자인합니다.
- 사진첩 게시판 개별 디테일 화면을 디자인합니다.
- 사진첩의 각 게시글에 조회수를 표시합니다.
- 사진첩 글쓰기 클릭 시 나타나는 업데이트 컴포넌트를 디자인합니다.

[feat]: 사진첩 페이지 디자인 (#85)

---

src/components/Navigation.js
src/pages/main/MainPage.js

resolve #91 
__`Router.js`__ 파일의 __div 요소__ 내부에서 __`MainPage.js`__ 컴포넌트를 불러올 때
**body 요소**가 자식요소로써 포함되어 Warning이 발생함.
__`MainPage.js`__ 파일의 JSX 부분에서 사용되는 **body 요소**를 **div 요소**로 변경함. 
- (**body** element → **div** element)

[fix]: 메인페이지 Warning(경고) 제거 (#91)

---

src/pages/register/RegisterPage.scss

resolve #89 
- 회원가입 버튼 내부 텍스트가 정상적으로 보이지 않음
- __fontawesome__ 요소의 수직 위치 변경
__`RegisterPage.scss`__ 파일 수정을 통해 문제 해결

[fix]: 회원가입 페이지 CSS 수정 (#89)

---

package-lock.json
package.json
src/pages/notice/NoticePage.js
src/pages/notice/NoticeUpdate.js
src/pages/notice/NoticeUpdate.scss

resolve #87
공지사항 작성 페이지만 다른 작성 페이지들과 ui가 달라 통일성이 떨어졌습니다.
공지사항 작성 페이지에서 사용하던 에디터를 제거하고, 다른 페이지들과 ui를 통일하였습니다.

[fix]: 공지사항 작성 페이지 ui 통일 (#87)

---

src/hooks/useAuth.js
src/pages/management/ManagementPage.js

resolve #94
관리자 페이지 접근 시 권한 확인 하지 않고 접근 하는 문제
관리자 페이지 접근 시 권한을 확인하여 admin이 아니라면 로그인 페이지로 이동

[feat]: 관리자 페이지 접근 권한 확인 (#94)

---

src/pages/management/MemberManage.js

resolve #95
관리자 페이지에서 회원 검색 기능 수정
기존에 회원 번호로 검색하던 부분을 이름으로 검색할 수 있도록 API 수정

[fix]: 관리자 페이지 회원 관리 기능 시스템 이름으로 검색 (#95)

---

src/components/Navigation.js
src/hooks/useAuth.js

resolve #96
API 변경
useAuth 와 navigation에 있던 API를 아래 API로 변경
/api/user/info  => /no-permit/api/user/info

[fix]: API 변경 (#96)

---

src/pages/photo/PhotoList.js
src/pages/photo/PhotoList.scss

resolve #102 
기존 사진첩 페이지에서 **반응형 기능** 구현을 위해 불필요하게<br />사용되던 요소들을 제거할 필요가 있었습니다.
- **반응형 기능** 구현을 위해 사용되었던 react의 **`state`** 및 __`EventListener`__ 를 제거하고<br />**`PhotoList.scss`** 파일에서 글이 배치되는 방법의 기준을 세워 기존과 동일한 **반응형 기능**을<br />구현하였습니다.
- 기존 글의 상단 부분을 기준으로 정렬되었던 부분을 이미지 크기에 따른 위치의 일관성을 위해<br />중앙을 기준으로 수직 정렬되도록 스타일을 조정하였습니다.
- 작업 사항 `1번`
- - -
- 작업 사항 `2번`

[fix]: 사진첩 페이지 반응형 기능 코드의 개선 (#102)

---

.gitignore
src/hooks/app-config.js

resolve #112
보안을 위해 서버 URL을 감춰야 하는 상황
- BASE_URL을 포함하고 있는 파일을 삭제하였습니다.
- gitignore에 해당 파일을 추가하여 github에 등록할 수 없도록 설정

[fix]: BASE_URL 주소 감춤 (#112)

---

src/hooks/useAuth.js

resolve #118
로그인에서 발생하는 오류 해결
- 로그인 api 수정
- refresh token 관련한 코드 제거

[bug]: 로그인 에서 발생하는 에러 해결 (#118)

---

src/pages/exam/ExamUpdate.js
src/pages/freeBoard/FreeBoardUpdate.js
src/pages/notice/NoticeUpdate.js
src/pages/photo/PhotoUpdate.js
src/pages/report/ReportUpdate.js
src/pages/seminar/SeminarUpdate.js
src/pages/subProject/ProjectUpdate.js

resolve #96
refresh token 제거에 따라 update에서 refresh token으로 접근하는 코드 삭제
삭제한 코드의 파일
- ProjectUpdate
- SeminarUpdate
- ReportUpdate
- PhotoUpdate
- NoticeUpdate
- FreeBoardUpdate
- ExamUpdate

[fix]: refresh token 제거에 따라 update 파일에 대한 코드 수정

---

src/pages/photo/PhotoList.js
src/pages/photo/PhotoList.scss

resolve #136 
사진첩 게시판에는 현재 `Pagination` 기능이 적용되어 있지 않아
DB에 등록된 게시글이 많아지면 불필요한 스크롤이 발생하기 때문에
타 게시판과 동일하게 `Pagination`을 적용하여 게시판을 효율적으로
관리할 수 있도록 하였습니다.
- 사진첩 페이지 내에 `Pagination` 기능을 추가합니다.
- 변경 전 사진첩 페이지
- 변경 후 사진첩 페이지

[feat]: 사진첩 컴포넌트 내 Pagination 기능 추가 (#136)

---

src/pages/freeBoard/FreeBoardPage.js
src/pages/main/Board.js
src/pages/notice/NoticePage.js
src/pages/photo/PhotoList.js

resolve #138 
**`PhotoList.js`** 파일 내에서 if-else문과 관련한 문법적 오류 및
`자유게시판` , `공지사항` , `메인페이지` 컴포넌트 내에서 사용자의 권한을
확인하는 요청문이 중복적으로 추가되었던 문제가 있었습니다.
- `FreeBoardPage.js` , `NoticePage.js` , `Board.js` 파일 내
중복적으로 사용된 myRole함수 호출 라인 제거
- `PhotoList.js` 파일 내 발생하였던 문법적 오류 라인 제거

[bug]: 사진첩 게시판 컴포넌트 내 문법적 오류 및 중복 권한 확인 요청 라인의 제거 (#138)

---

.env
src/Router.js
src/components/AuthGuard.js
src/components/Navigation.js
src/hooks/boardServices.js
src/hooks/useAuth.js
src/hooks/useFetch.js
src/pages/login/LoginPage.js
src/pages/main/Board.js
src/pages/notice/NoticeDetailPage.js
src/pages/notice/NoticePage.js
src/pages/notice/NoticeUpdate.js
src/utils/api.js

[bug]: 사용자 인증 관련 문제 해결 (#140)

---

src/pages/freeBoard/FreeBoardPage.js

[bug]: 자유게시판 컴포넌트 내 잘못된 값으로 요청한 모듈 함수 호출 인수 수정 (#148)

---

src/components/Navigation.js
src/hooks/boardServices.js
src/hooks/useAuth.js
src/pages/exam/ExamDetailPage.js
src/pages/freeBoard/FreeBoardDetailPage.js
src/pages/freeBoard/FreeBoardPage.js
src/pages/login/LoginPage.js
src/pages/modifyUserInfo/CheckPwPage.js
src/pages/notice/NoticeDetailPage.js
src/pages/notice/NoticePage.js
src/pages/photo/PhotoList.js
src/pages/report/ReportPage.js
src/pages/seminar/SeminarPage.js
src/pages/subProject/ProjectPage.js
src/utils/api.js

[bug]: 전체 점검 완료 (#147)

---

src/pages/exam/ExamUpdate.js
src/pages/freeBoard/FreeBoardPage.js
src/pages/freeBoard/FreeBoardUpdate.js
src/pages/login/LoginPage.js
src/pages/main/Board.js
src/pages/main/Schedule.js
src/pages/management/ScheduleManage.js
src/pages/notice/NoticeUpdate.js
src/pages/photo/PhotoUpdate.js
src/pages/report/ReportUpdate.js
src/pages/seminar/SeminarUpdate.js
src/pages/subProject/ProjectUpdate.js
src/utils/api.js

resolve #151 
- 홈페이지에서 특정 컴포넌트에 접근 시 요청하는 API의
response 값을 확인하기 위해 사용하는 불필요 `console.log`
함수를 주석 처리 및 제거하여 요청받는 값을 보이지 하도록 수정하였습니다.
- 불필요하게 `console.log` 함수가 사용되는 파일에서 해당 코드를 annotation 및 제거

[fix]: response 응답 여부 확인용 불필요 console.log 함수 일괄 주석 처리 및 제거 (#151)

---

src/components/Navigation.js
src/pages/main/Board.js

resolve #156 
메인페이지 내 위치한 공지사항 게시글 리스트가
출력되지 않는 문제가 있었습니다.
- **`Board.js`** 파일 수정
- 해결

[bug]: 메인 페이지 내 공지사항 리스트가 출력되지 않던 버그 수정 (#156)

---

src/Router.js
src/pages/exam/ExamPage.js
src/pages/login/LoginPage.js
src/pages/management/ManagementPage.js
src/pages/notice/NoticePage.js

resolve #153 
특정 컴포넌트에 접속 시 접근한 유저의 권한에 맞게 예외처리가
이뤄지지 않는 부분들에 대한 올바르게 수정하였습니다.
- 접근 가능 여부 확인 처리가 정상적으로 이뤄지지 않는
컴포넌트들을 일괄적으로 확인 후 수정하였습니다.

[fix]: 컴포넌트 별로 유저의 권한에 알맞게 접근 및 차단이 가능하도록 수정 (#153)

---

src/pages/management/BoardManage.js

resolve #162 
관리자 페이지 내에서 사용되는 **`게시판 생성`** API 호출 문장에 누락된 부분이 있어
정상적으로 게시판을 생성하지 못 하는 버그가 발견되었습니다.
- **`BoardManage.js`** 파일 내 api.post 코드 올바르게 수정
- 수정 전
- 수정 후

[bug]: 게시판 생성 API 호출문 올바른 형식으로 수정 (#162)

---

src/Router.js
src/pages/notFound/NotFound.js
src/pages/notFound/NotFound.scss

resolve #166 
기존 **`Router.js`** 에 등록되어 있지 않은 주소를
입력하여 접근할 경우 메인 섹션에 아무런 내용이 표시되지
않았는데, 해당 작업이 사용자에게 잘못된 접근임을 알려주기
위해여 NotFound 컴포넌트를 추가하였습니다.
- Router에 등록되지 않은 주소에 접근 시 NotFound 컴포넌트가 나타나도록
Route path 추가 및 NotFound 컴포넌트, SCSS(스타일) 코드 추가
- 추가 전 페이지
- 추가 후 페이지

[feat]: NotFound 페이지 추가 (#166)

---

src/components/Navigation.js
src/hooks/useAuth.js

resolve #168 
로그인 후 직접 `로그아웃` 버튼을 누르거나 만료 시간 이후에
로그아웃이 되었을 때 여전히 액세스 토큰이 남아 있어  비회원인
상태에서 권한이 필요한 컴포넌트에 접근 시 모두 허용되던 문제가
발견되어 수정하였습니다.
- `Navigation.js` 및 `useAuth.js` 파일 내 코드를 수정하였습니다.
(만료 시간 이후 유저 정보를 불러오는 APi 사용 시 에러가 발생하면 액세스 토큰(쿠키)를
제거하는 방법으로 코드를 수정하였습니다)
- 해결 이후

[bug]: 로그아웃 버그 수정 (#168)

---

src/components/Navigation.js
src/pages/exam/ExamUpdate.js
src/pages/freeBoard/FreeBoardUpdate.js
src/pages/management/BoardManage.js
src/pages/management/MemberManage.js
src/pages/management/ScheduleManage.js
src/pages/notice/NoticePage.js
src/pages/notice/NoticeUpdate.js
src/pages/photo/PhotoUpdate.js
src/pages/report/ReportUpdate.js
src/pages/seminar/SeminarUpdate.js
src/pages/subProject/ProjectUpdate.js

resolve #170 
로그인 시 발급되는 액세스 토큰을 확인 후 호출이 가능한 API들이 있는데,
토큰 유효 시간이 만료되고 해당 API들을 사용하면 정상적으로 처리가 되지
못하여 에러가 발생하였습니다.
- 액세스 토큰을 확인하고 호출하는 모든 API들이 위치한 코드 수정하였습니다.
- 에러 사진
> (예시, 공지사항에서 글을 작성하였지만, 토큰 유효 시간이 지나 `작성완료` 버튼을 누르면 API가 정상적으로 처리되지 못 하여 에러가 발생하는 상황)
- 액세스 토큰 만료 & 비회원인 상황과 일반 회원인 상태에서 공지사항 내 `작성하기` 버튼 클릭 시 발생하던 에러가 있어서 수정하였습니다.

[bug]: 토큰 유효 시간 만료 후 API 호출 시 발생하는 버그 제거 및 특정 컴포넌트 접근 시 권한 별로 알맞게 차단되도록 코드 수정 (#170)

---

src/components/Comment.js
src/components/Comment.scss
src/pages/exam/ExamDetailPage.js
src/pages/freeBoard/FreeBoardDetailPage.js
src/pages/notice/NoticeDetailPage.js
src/pages/photo/PhotoDetail.js
src/pages/photo/PhotoDetail.scss
src/pages/report/ReportDetailPage.js
src/pages/seminar/SeminarDetailPage.js
src/pages/subProject/ProjectDetailPage.js

resolve #155
게시판의 댓글 기능을 추가합니다.
각각의 게시판에 댓글 기능을 추가합니다.
- 자유게시판
- 공지사항
- 사진첩
- 자료실
- - 특강자료
- - 활동보고서
- - 소규모 프로젝트
- - 족보

[feat]: 게시판 댓글 기능 추가 (#155)

---

src/pages/modifyUserInfo/CheckPwPage.js
src/pages/modifyUserInfo/ModifyUserInfoPage.js
src/pages/modifyUserInfo/ModifyUserInfoPage.scss

resolve #172 
- 로그인 시 발급되는 액세스 토큰을 확인 후 호출이 가능한 API들이 있는데,
`정보수정 관련 페이지` 내에서 토큰 유효 시간이 만료되고 해당 API들을 사용하면
정상적으로 처리가 되지 못하여 에러가 발생하였습니다.
- 백엔드 API와 프론트 API호출 형식의 차이로 인하여 에러가 발생하였습니다.
- 정보수정 페이지 UI 요소 비대칭 요소 수정이 필요하였습니다.
- **`CheckPwPage.js`** , **`ModifyUserInfoPage.js`** , **`ModifyUserInfoPage.scss`** 파일 내 코드 추가 및 수정
- 학번에 대한 수정은 아직 백엔드에서 작업되지 않아 해당 페이지 내에서 학번 변경 시 값이 변경되지는 않습니다.
- `학년` 요소 추가 및 비대칭 요소 해결 후
- 버그 제거 후 (GIF파일이 첨부되어 있어 화면에 표시되기까지 시간이 다소 소요될 수 있습니다)

[bug]: 정보수정 컴포넌트 버그 제거 (#172)

---

src/pages/register/RegisterPage.js

resolve #174 
회원가입 페이지 내에서 중복된 학번 및 이메일로
가입 시도 시 별도의 예외처리를 해 주는 코드가
없어 에러가 발생하는 문제가 있었습니다.
- **`RegisterPage.js`** 파일 수정
- 해결 후(중복 학번 처리)
- 해결 후(중복 이메일 처리)

[bug]: 회원가입 컴포넌트 내 중복 정보에 대한 예외처리 코드 추가 (#174)

---

src/components/Navigation.js

resolve #177 
접속자 기능을 제거함에 따라 홈페이지 내
**`접속자`** 확인 요소를 제거하였습니다.
- **`Navigation.js`** 파일 내 접속자 요소 제거
- 제거 전
- 제거 후

[fix]: 네비게이션 컴포넌트 내 접속자 요소 제거 (#177)

---

src/components/Comment.js
src/hooks/usePostServices.js
src/pages/exam/ExamDetailPage.js
src/pages/freeBoard/FreeBoardDetailPage.js
src/pages/notice/NoticeDetailPage.js
src/pages/photo/PhotoDetail.js
src/pages/report/ReportDetailPage.js
src/pages/seminar/SeminarDetailPage.js
src/pages/subProject/ProjectDetailPage.js

resolve #182
- 현재 게시글 내 `게시글 삭제` 기능이 존재하지 않아
사용자가 게시글을 제거하지 못 하는 문제가 있어 해당
요소를 추가하고자 하였습니다.
- 게시글 컴포넌트 내에 `게시글 삭제` 버튼과 기능을 추가하였습니다.
- 추가 전
- 추가 후
- 소규모 프로젝트 및 족보 게시판 내 스타일이 적용되어 있지 않았음
- 수정 후

[feat]: 게시글 삭제 기능 추가 (#182)

---

src/components/Comment.scss
src/pages/exam/ExamDetailPage.js
src/pages/exam/ExamUpdate.js
src/pages/freeBoard/FreeBoardDetailPage.js
src/pages/freeBoard/FreeBoardUpdate.js
src/pages/notice/NoticeDetailPage.js
src/pages/notice/NoticeUpdate.js
src/pages/report/ReportDetailPage.js
src/pages/report/ReportUpdate.js
src/pages/seminar/SeminarDetailPage.js
src/pages/seminar/SeminarUpdate.js
src/pages/subProject/ProjectDetailPage.js
src/pages/subProject/ProjectUpdate.js

resolve #191
게시판에서 여러개의 파일을 등록할 수 있도록 수정하였습니다.
수정한 페이지
- 자유게시판
- 족보
- 공지사항
- 특강자료
- 활동보고서
- 소규모프로젝트

[fix]: 첨부파일 여러 개 추가 가능하도록 수정

---

src/components/Footer.js

resolve #213 
현재 샘마루 홈페이지 개발 인원이 누락되어 있는
문제가 있어서 알맞게 추가하였습니다.
- 백엔드 팀 개발 인원 추가
- 기존 화면
- 수정 후

[fix]: 샘마루 동아리 홈페이지 백엔드 개발 인원 추가 (#213)

---

src/pages/login/LoginPage.js

resolve #234
현재 동아리 홈페이지 내 보안 상의 이유로 **`자동 로그인`** 기능 추가 소요가
사라지게 되어 해당 UI 요소를 제거하였습니다.
- **`LoginPage.js`** 컴포넌트 내 `자동 로그인` 요소 제거
- 기존 로그인 페이지
- 제거 후 로그인 페이지

[fix]: 자동 로그인 요소 제거 (#234)

---

src/components/Comment.js

[bug]: 댓글 있는 게시판 호출 에러 해결 (#236)

---

public/assets/css/main.css
src/hooks/boardServices.js
src/pages/exam/ExamPage.js
src/pages/freeBoard/FreeBoardPage.js
src/pages/notice/NoticePage.js
src/pages/report/ReportPage.js
src/pages/seminar/SeminarPage.js
src/pages/subProject/ProjectPage.js

resolve #201
현재 홈페이지 내에 존재하는 모든 게시판 내에서 특정 게시글을
조회하기 위해서는 별도로 pagination 기능을 이용하여 직접
찾아야 하는 번거로움이 있었는데, 게시글 검색 기능을 추가하여
좀 더 간편하게 게시글에 접근할 수 있도록 하고자 하였습니다.
- `사진첩 게시판`을 제외한 모든 게시판에서 특정 조건에 의한 게시글 검색 기능이 추가됩니다.
- 게시글 검색 란의 스타일이 변경됩니다.
- **`Pagination`** 위치가 좀 더 게시글과 가깝게 조정되었습니다.
- 스타일 변경 전
- 스타일 변경 후
---
- 기능 추가 전
https://user-images.githubusercontent.com/56868605/207845434-6cd4893f-db6d-4121-b4b0-b60c68f362f7.mov
- 기능 추가 후
https://user-images.githubusercontent.com/56868605/207845525-4353ccd4-a44c-4970-8ab7-51e5dcd24c2d.mov

[feat]: 게시글 검색 기능 추가 및 스타일 수정 (#201)

---

src/pages/login/LoginPage.jsx
src/pages/login/LoginPage.scss

resolve #253 
현재 로그인 페이지 입력 폼에서 사용되고 있는 input 요소의
가로 너비의 크기가 기기 해상도 및 운영체제(`Windows 10`)에
따라 의도하지 않은 크기로 나타나는 문제와, 로그인 컴포넌트 이외의
컴포넌트(Navigation, Footer) 영역 클릭 시 로그인 컴포넌트 내부
input 요소의 너비가 변경될 때 X버튼은 나타나지 않는 문제가 있어서
해당 부분을 수정하였습니다.
- `LoginPage.jsx` 파일의 로직을 수정하였습니다.
- `LoginPage.scss` 파일 내 스타일링 관련 코드를 수정하였습니다.
- 이전 페이지(너비가 버튼과 일치하지 않음, `Windows 10` 환경)
- 해결 후 `Windows 10` 환경
- 로그인 페이지 이외의 컴포넌트 공간 클릭하여 input 요소의 너비가 변경될 때 `X 버튼`이 나타나지 않는 문제가 있음
- 해결 후 (다른 컴포넌트[Navigation, Footer]의 영역 클릭 이후에도 X버튼이 정상적으로 나타남)

[fix]: 운영체제에 따른 로그인 페이지 내 input 요소 너비 크기 이슈 해결 및 코드 개선 (#253)

---

.github/ISSUE_TEMPLATE/bug.md

resolve #269 
기존에 `버그 발생`이라는 표현은 오로지 버그가 발생하였음을 표현하는 말이므로
발견과 동시에 해당 버그가 수정되는 작업으로 연계되게끔 이슈를 생성할 수 있도록
`버그 발생`이라는 표현에서 `버그 수정`이라는 말로 변경하고자 하였습니다.
- `/.github/ISSUE_TEMPLATE/bug.md` 파일 내 about 속성명 변경
- 수정 후 텍스트

[fix]: Github [BUG] Issue 템플릿 내 about 속성값 변경 (#269)

---

src/components/Navigation.jsx
src/components/Navigation.scss

resolve #293 
현재 모바일 디바이스 내에서 홈페이지에 접속 후 홈페이지 상단의 `로그인` 혹은 `회원가입`
요소 클릭 시 정상적으로 해당 페이지에 이동하지 못 하는 버그가 발견되어 수정하였습니다.
- 기존 `로그인`, `회원가입` 요소로 사용되던 `Link` 태그를 `button` 태그로 변경 후
라우팅용 이벤트 함수 등록
- 로그인/회원가입 버튼 스타일 조정
- 기존 버그
- 버그 해결 후

[bug]: 모바일 디바이스 내 로그인/회원가입 요소 터치 불가 버그 제거 (#293)

---

src/components/Footer.jsx
src/components/Navigation.jsx
src/pages/about/IntroClubPage.js
src/pages/exam/ExamPage.jsx
src/pages/findUser/FindUserPage.jsx
src/pages/freeBoard/FreeBoardPage.jsx
src/pages/login/LoginPage.jsx
src/pages/main/MainPage.jsx
src/pages/main/MainPage.scss
src/pages/management/ManagementPage.jsx
src/pages/notice/NoticePage.jsx
src/pages/report/ReportPage.jsx
src/pages/seminar/SeminarPage.jsx
src/pages/subProject/ProjectPage.jsx

resolve #299 
홈페이지에서 불필요한 페이지 및 UI 요소들을 일괄적으로 제거 및 수정하였습니다.
- 메인페이지 내 일부 UI 요소 제거
- 게시판 테이블 데이터 X축 스크롤 추가
- 게시판 페이지 상단 location 표시 UI 요소 제거
- 관리자 페이지 내 불필요 tab 제거
없습니다

[fix]: 홈페이지 디자인 일괄 수정 (#299)

---

src/pages/bulletin.scss
src/pages/modifyUserInfo/ModifyPassword.scss

resolve #301 
비밀번호 변경 페이지 및 게시판 내용에 대한 CSS 스타일을 수정하였습니다.
- 비밀번호 변경 페이지 컴포넌트 CSS 수정
- 게시판 내용에 대한 CSS 스타일 수정
없습니다

[fix]: 비밀번호 변경 페이지 및 게시판 내용 CSS 스타일 수정 (#301)

---

src/pages/freeBoard/FreeBoardPage.jsx
src/pages/management/ManagementPage.jsx
src/pages/photo/PhotoList.jsx

resolve #303 
로그인을 하지 않은 비회원의 경우에도 자유게시판 및 사진첩 페이지에 접근이 가능하도록
관련 로직을 수정하였습니다.
- 자유게시판 비회원 접근 허용 로직 수정
- 사진첩 게시판 비회원 접근 허용 로직 수정
없습니다

[fix]: 자유게시판, 사진첩 페이지 비회원 접근 허용 (#303)
